#!/bin/bash

# neovim
brew tap neovim/neovim
brew install neovim

# Vundle
git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim

# custom vimrc
cp $HOME/.mysh/rc/.vimrc ~/.vimrc

echo "To finish Vundle launch `vim` and run `:PluginInstall`"
echo "To finish Vundle launch `vim` and run `:PluginInstall`"
