#!/usr/bin/env bash

git clone https://github.com/nodenv/nodenv.git ~/.nodenv

cd ~/.nodenv && src/configure && make -C src

export PATH="$HOME/.nodenv/bin:$PATH"

# nodenv-build
git clone https://github.com/nodenv/node-build.git $(nodenv root)/plugins/node-build

# nodenv-rehash
git clone https://github.com/nodenv/nodenv-package-rehash.git "$(nodenv root)"/plugins/nodenv-package-rehash

# nodenv-update
git clone https://github.com/nodenv/nodenv-update.git "$(nodenv root)"/plugins/nodenv-update

