#!/usr/bin/env bash

git clone https://github.com/nodenv/nodenv.git ~/.nodenv

cd ~/.nodenv && src/configure && make -C src

export PATH="$HOME/.nodenv/bin:$PATH"

# node-build
git clone https://github.com/nodenv/node-build.git $(nodenv root)/plugins/node-build

# node-rehash
git clone https://github.com/nodenv/nodenv-package-rehash.git "$(nodenv root)"/plugins/nodenv-package-rehash
