#!/bin/usr/bash

# Install brew. Other stuff will be installed via brew
# $HOME/.mysh/modules/brew

# java environment manager
$HOME/.mysh/modules/jenv

# node environment manager
$HOME/.mysh/modules/nodenv

# neovim
# $HOME/.mysh/modules/neovim

# install mysh
$HOME/.mysh/modules/mysh

# install vim
$HOME/.mysh/modules/vim

