#!/bin/usr/bash

# Install brew. Other stuff will be installed via brew
$HOME/.mysh/modules/brew

# Install git (always needed)
$HOME/.mysh/modules/git

# java environment manager
$HOME/.mysh/modules/jenv

# node environment manager
$HOME/.mysh/modules/nodenv

# neovim
$HOME/.mysh/modules/neovim

# install mysh
$HOME/.mysh/modules/mysh